### ISSUE TITLE
Failed to check checksum of TcpPacket

### ISSUE THREAD

**Issue by radioegor146** [chmorgan/packetnet#106]
The call to `TcpPacket.IsValidChecksum` lead to that exception:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at PacketDotNet.Utils.ChecksumUtils.Sum(Byte*, Int32, UInt64)
   at PacketDotNet.Utils.ChecksumUtils.OnesSum(Byte*, Int32, Byte*, Int32)
   at PacketDotNet.Utils.ChecksumUtils.OnesSum(PacketDotNet.Utils.ByteArraySegment, Byte[])
   at PacketDotNet.TransportPacket.IsValidChecksum(TransportChecksumOption)
```
I can't give the packet that caused that issue, because it happend on production where we do not collect all packets.

**Comment by radioegor146** [comment]
Well, as it happened - it was a corrupted (trimmed) packet. But probably it'll better if somebody could add bound checks due to the fact that this exception cannot be caught.

**Comment by Phyxion** [comment]
Perhaps just for `IsValidChecksum` it's possible to add a check if it's within the bounds. I'd rather not reduce performance for calculating all checksums (a check was there before that throwed, but this costed more time than calculating the actual checksum). I'll think about this. 
FWIW, you can avoid most of these problems by allocating enough space while reading packets, ensure packets have at least a buffer with the link layer maximum (~1514 bytes).
