### ISSUE TITLE
Strange exception at the end of method

### ISSUE THREAD

**Issue by radioegor146** [chmorgan/packetnet#107]
```
System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at PacketDotNet.Utils.ByteArraySegment.ActualBytes()
   at ********.HandlePacketAsync(DateTime packetTimeStamp, IPPacket packet, Object packetData) in ******\TcpParser.cs:line 167
```

The exception was at the end of one async function that even doesn't call `ActualBytes`. I can't give the packet that caused that issue, because it happend on production where we do not collect all packets.

**Comment by chmorgan** [comment]
Possible to catch the exception and store the offending packet to disk?
That might be the only way for us to fix this and the other issue you
reported.

Regards,
Chris

**Comment by radioegor146** [comment]
Ok, I'll try my best to catch bad packets.

**Comment by Phyxion** [comment]
This most likely is a corrupted packet, but without the actual packet it's not really possible to check any further.

**Comment by radioegor146** [comment]
Well, it was a corrupted packet, thanks.
