### ISSUE TITLE
Switch symbols to snupkg

### ISSUE THREAD

**Issue by PhyxionNL** [chmorgan/packetnet#110]
See https://github.com/appveyor/ci/issues/2753 and https://help.appveyor.com/discussions/problems/27680-deployment-issue-nuget.

**Comment by Phyxion** [comment]
Not sure if anything needs to be flipped in AppVeyor for this, so probably best for @chmorgan to do.

**Comment by chmorgan** [comment]
Hmm. What is a snupkg? If anyone wants to propose a GitHub workspace file change I'll look at merging it. I saw some points about GitHub not support snupkg yet though.

**Comment by Phyxion** [comment]
It's a normal NuGet package with symbols. Now that AppVeyor is gone it might not be needed anymore.
<IncludeSymbols>true</IncludeSymbols> will probably be enough.

**Comment by chmorgan** [comment]
Where do we set that? I don't see any options and can't find a mention of IncludeSymbols text in any files.

**Comment by chmorgan** [comment]
@PhyxionNL I noticed nuget was saying a symbols package was pushed. Does this mean we are all set now and can close this issue out?

**Comment by PhyxionNL** [comment]
Yeah, it's good now it seems 👍
