### ISSUE TITLE
Can we drop .netframework 4.5 now?

### ISSUE THREAD

**Issue by chmorgan** [chmorgan/packetnet#112]
Hello @Phyxion. I can't recall why we are releasing for .netframework 4.5 at this point. Thoughts on dropping that and targeting .net core 2.0 only?

**Comment by Phyxion** [comment]
.NET 4.5.2 is still supported and it's rather likely some applications are still on that. I also don't really see a reason to drop it at the moment  as nothing is blocked because of supporting it.

**Comment by chmorgan** [comment]
@Phyxion hmm. I'm trying to get away from appveyor as its been a huge sink of my time getting things working from the .yml file and move to GitHub. Let me see if github's ci system can add the .netframework dependencies required to build, maybe by installing mono.

**Comment by Phyxion** [comment]
That should be possible, I think you can use windows-latest. I found a guide here if it helps:
https://timheuer.com/blog/building-net-framework-apps-using-github-actions/

Moving away from AppVeyor sounds like a good idea though, it's such a mess to configure. I'd like to keep the existing configuration on NuGet, i.e. .NET Framework 4.5.2 and .NET Standard 2.0, then pretty much every platform is supported. Any lower .NET Standard is missing too many APIs for it to work.

**Comment by chmorgan** [comment]
k, I think that could work

**Comment by Phyxion** [comment]
Some other examples here, might be a good starting point:
https://github.com/search?p=1&q=windows-latest+nuget&type=Code

**Comment by chmorgan** [comment]
Looks like things are working with the GitHub path.
