### ISSUE TITLE
Recent memory managment changes do not work with large capture files

### ISSUE THREAD

**Issue by twa89** [chmorgan/packetnet#120]
When I upgraded from sharppcap 5.1 to 5.3 a new version of PacketDotNet also came with the upgrade.  Now when I parse large wireshark files, ones larger than 1.6 GB, packetDotNet crashes every time with outOfMemory exceptions.

If I rollback to SharpPcap 5.1 it works perfectly, even capture files over 6 GB in size.

**Comment by PhyxionNL** [comment]
This needs to be opened in Sharpcap.

**Comment by chmorgan** [comment]
@PhyxionNL any thoughts what might be causing the issue? Nothing comes to mind as a change that would result in this issue.

**Comment by PhyxionNL** [comment]
I have no idea, I do not use SharpPcap myself. Without some example files from @twa89 it might be hard to pinpoint the problem.
