### ISSUE TITLE
Re-write for no reason

### ISSUE THREAD

**Issue by syndrome5** [chmorgan/packetnet#125]
Hello,

This specific line is annoying if we are setting an Ethernet Type out of the switch scope provided. We need to re-write the type after the PayloadPacket set. I think we can remove or set a warning message on debug that uncommon Ethernet type is used.

https://github.com/chmorgan/packetnet/blob/86e8aaaf59590cb6c81fe19c3ff350f79eebcdc5/PacketDotNet/EthernetPacket.cs#L153

Regards

**Comment by PhyxionNL** [comment]
I think the default statement can be removed completely. If any payload is set that isn't known to the library then it's up for the user to set. Feel free to submit a PR for this.
