### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by lovejotd** [chmorgan/packetnet#128]
This is less of an issue and more a feature request possibly?  But I was wondering if there was a way to get the information column, similar to what you see in wireshark, from the pcap file?  Is this something we could easily add to this library?  or does anyone know how that is created?  Thanks!

**Comment by chmorgan** [comment]
@lovejotd can you post an image showing what you mean? We have colorized ToString() output today btw.

I added the ability to specify the verbosity to the capture example, can you see if one of these output modes provides something like what you are looking for?

https://github.com/chmorgan/packetnet/pull/129

**Comment by chmorgan** [comment]
And those changes have landed on master as well. Let me know what you think.

**Comment by chmorgan** [comment]
@lovejotd closing this one out as I think the updated capture example shows how to get more detailed packet information. Please reopen if you have suggestions or this isn't exactly what you are looking for.
