### ISSUE TITLE
GRE decoding not correct (wrong byte and false bitmask)

### ISSUE THREAD

**Issue by Bart-Baekelandt** [chmorgan/packetnet#131]
The GRE protocol is not correctly parsed by the PacketNet library

in GrePacket.cs

original code :
public bool HasCheckSum => 8 == (Header.Bytes[Header.Offset + 1] & 0x8);
public bool HasKey => 2 == (Header.Bytes[Header.Offset + 1] & 0x2);
public bool HasReserved => 4 == (Header.Bytes[Header.Offset + 1] & 0x4);
public bool HasSequence => 1 == (Header.Bytes[Header.Offset + 1] & 0x1);

proposal for new code :
public bool HasCheckSum => 0x80 == (Header.Bytes[Header.Offset + 0] & 0x80);
public bool HasKey => 0x20 == (Header.Bytes[Header.Offset + 0] & 0x20);
public bool HasReserved => false; // 4 == (Header.Bytes[Header.Offset + 1] & 0x4);
public bool HasSequence => 0x10 == (Header.Bytes[Header.Offset + 0] & 0x10);

See also https://en.wikipedia.org/wiki/Generic_Routing_Encapsulation

Example where the original code fails :
[gre_seq_2.zip](https://github.com/chmorgan/packetnet/files/6346973/gre_seq_2.zip)

**Comment by PhyxionNL** [comment]
Can you submit a PR for this and a test @Bart-Baekelandt?

**Comment by Bart-Baekelandt** [comment]
![gre_screenshot](https://user-images.githubusercontent.com/43503534/115627766-dd69f100-a2ff-11eb-9014-6873474d55d3.PNG)

See also decoding in Wireshark

**Comment by PhyxionNL** [comment]
Should be fixed now, so closing.
