### ISSUE TITLE
IPortPacket

### ISSUE THREAD

**Issue by shargon** [chmorgan/packetnet#15]
Could be usefull a IPortPacket interface for TcpPacket and UdpPacket

```
public interface IPortPacket
{
        /// <summary> Fetch the port number on the source host.</summary>
        ushort SourcePort { get; set; }
        /// <summary> Fetches the port number on the destination host.</summary>
        ushort DestinationPort { get; set; }
}
```

or add it to TransportPacket

**Comment by chmorgan** [comment]
Are there any other packets that are port packets? I see the idea but I'd like to be strict about not layering types if it isn't a natural thing that people associate between those types and if it only saves a few lines of code on the users side.

**Comment by Wootness** [comment]
There are ports in the SCTP protocol, which is also a transport layer protocol.

**Comment by chmorgan** [comment]
I think I'd have to see how this might simplify the code before considering how we might integrate a change like this. While I see some gain it isn't immediately obvious how this would clarify or improve the code so I'd have to see that before merging it in. I'm going to close this out for now but if you have another comment we can reopen this to continue discussion.
