### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by raspi** [chmorgan/packetnet#19]
Could you please publish latest release as NuGet package?

**Comment by chmorgan** [comment]
Hello.

I'd like to. I'm working on it but someone is using the SharpPcap and PacketDotNet IDs on Nuget. I've reached out to the guy using those ID values but the policy is to wait 30 days before they take any action and it hasn't been 30 days yet, it will be in another week or so and I'll reach back out to the nuget guys about it.

Chris

**Comment by termhn** [comment]
Any update on this? :P

**Comment by chmorgan** [comment]
Yep. Discussing it with someone that put together the packages on Nuget. Hope to have some updated packages in the next few weeks.

**Comment by chmorgan** [comment]
@termhn I'm stuck on the nuget packages. nuget can't pack on Linux and I don't have a Windows license.

**Comment by chmorgan** [comment]
@raspi packages pushed!
