### ISSUE TITLE
How to construct packets (like ICMPv4Packet)

### ISSUE THREAD

**Issue by UlyssesWu** [chmorgan/packetnet#20]
How to construct a valid ICMPv4Packet using PacketDotNet?

Currently I can only use `PcapDotNet.Packets` to construct these packets.

**Comment by chmorgan** [comment]
Hello.

If you know what an ICMPv4Packet looks like you can apply the same approach as here: https://github.com/chmorgan/packetnet/blob/master/Examples/ConstructingPackets/Main.cs

I think ICMPv4 is an EthernetPacket that contains an IPv4 packet that contains an ICMP packet. (I'm using packet when I probably should use datagram though).

Can you try the same approach as in that Main.cs file and let me know how you make out? If you did update the Main.cs with an ICMPv4Packet I'd be open to a pull request to add to that example.
