### ISSUE TITLE
Target older .NET framework by default

### ISSUE THREAD

**Issue by raspi** [chmorgan/packetnet#21]
Current solution [targets .NET framework 4.6.1](https://github.com/chmorgan/packetnet/blob/cabc30be3f0af873f20a195a2effc1371a49eec9/PacketDotNet/PacketDotNet.csproj#L9). Windows Server 2012 R2 and 8.1 [was shipped with 4.5.1](https://en.wikipedia.org/wiki/.NET_Framework_version_history) and is still widely used and no newer version might be available because of policies.

Could 4.5.1 be the default?

**Comment by chmorgan** [comment]
@raspi It looks like 4.5.2 is still supported but 4.5.1 is end-of-life, https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

what about moving to 4.5.2 instead?

**Comment by raspi** [comment]
R2 is supported until 2023 - https://support.microsoft.com/en-us/lifecycle/search?alpha=Windows%20Server%202012%20R2%20Standard . Older NuGet version was using .NET fw 3.5 and sharppcap used that also. For the best backwards compatibility as old as possible .NET fw target should be used. Another way could be to release multiple targets like [SQLite does as an example](https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki).

**Comment by chmorgan** [comment]
@raspi I think we are talking about two different things. Yes, Windows Server 2012 R2 is supported until 2023, but only .net 4.5.2 is currently supported, not 4.5.1. See https://support.microsoft.com/en-us/lifecycle/search?alpha=Microsoft%20.NET%20Framework%204.5.1

**Comment by raspi** [comment]
Yes the .NET fw 4.5.1 might be deprecated (for only ~7 months now) but it doesn't mean that people are running newer version if they're using R2 for example. A lot of people are running .NET fw which was shipped with the OS ie. 4.5.1 in R2 and 8.1. 

My use case is OSS LLDP agent which adds LLDP support for older Windows versions so that network and sysadmins jobs are made easier who are still running older OSes in their environments. Their company came up with the policies to not upgrade anything until the long term support ends.

**Comment by chmorgan** [comment]
@raspi ahh ok. If it's forwards compatible then I have no problem rebuilding for 4.5.1. Let me check that doing so will work ok here under mono and I can push out a new set of versions sometime in the near future.

**Comment by chmorgan** [comment]
@raspi I've updated the .net target version to 4.5.1. Would you mind testing out the 'net_4_5_1' branch or would it make sense for me to send you .nupack files? I'd like it to be tested prior to bumping versions and releasing new packages etc.

**Comment by raspi** [comment]
I was able to compile both packetnet and sharppcap in VS 2017 CE. There were no build or runtime errors with net_4_5_1 branch and my program.

**Comment by chmorgan** [comment]
@raspi published new nuget versions of sharppcap and packetdotnet that target 4.5.1
