### ISSUE TITLE
PayloadData instead of PayloadPacket

### ISSUE THREAD

**Issue by Heshyo** [chmorgan/packetnet#23]
I parse a packet by doing with `Packet.ParsePacket(LinkLayers.Ieee80211_Radio, buffer)`, which gives me a `RadioPacket`.

That `RadioPacket.PayloadPacket` contains a `QosDataFrame` which itself contains some `PayloadData`, but no `PayloadPacket`.

In Wireshark I still see `Logical-Link Control`, then `IPv4`, then `TCP`, then finally some payload data (see [OnePacket.zip](https://github.com/chmorgan/packetnet/files/1204001/OnePacket.zip)). Am I doing something wrong, or are things not yet implemented?

I tried with the latest release 0.14.0, as well as with the current master.

**Comment by chmorgan** [comment]
Hello.

Have you looked to see if there are any tests for radio packets? It may be that this isn't supported. In any case, if you can send me a .pcap file with a few of these packets I can write a unit test to parse them.

chmorgan@gmail.com is my direct email address.

Chris

**Comment by Heshyo** [comment]
Hi Chris,

There's indeed a RadioPacketTest that uses 80211_plus_radiotap_header.pcap

In my case the RadioPacket is correctly parsed, and it correctly contains a
PayloadPacket.

That PayloadPacket is a QosDataFrame (there's also a test for it:
QosDataFrameTest that uses 80211_qos_data_frame.pcap), but this
QosDataFrame only contains a PayloadData, while I feel it should contain a
PayloadPacket of type "Logical-Link Control".

I'm not seeing any test or class for Logical-Link Control or LLC, so maybe
that's what's missing?

I already attached one packet to the issue on GitHub, but I'm attaching
another pcap file with more packets here too.

Regards,
  Henri


2017-08-07 20:39 GMT+08:00 Chris Morgan <notifications@github.com>:

**Comment by chmorgan** [comment]
Yep, Logical-Link control isn't implemented at this point so there was no decoding of the data inside of those data frames. Let me try to put something together to parse that. Fortunately the rest of the parsing code is present so once the LLC is parsed I think you'll get a fully decoded packet.

**Comment by chmorgan** [comment]
@Heshyo can you test out the qosdata branch and let me know if that resolves the issue for you?

**Comment by Heshyo** [comment]
Thanks Chris. I haven't extensively tested it, but it seems to be working pretty well with my current test file, thanks a lot!
