### ISSUE TITLE
Support the PROFINET Protocol as EtherType

### ISSUE THREAD

**Issue by singularity0821** [chmorgan/packetnet#28]
Would it be possible to support the PROFINET protocol as a valid EtherType?

This would be ```0x8892``` PROFINET Protocol.

**Comment by chmorgan** [comment]
Do you mean simply adding that entry to the list of EtherTypes or adding proper decoding for profinet?

**Comment by singularity0821** [comment]
I mean simply adding it to the list of EtherTypes.

**Comment by chmorgan** [comment]
Change pushed to master.
