### ISSUE TITLE
Problem with .Net Core package, Ubuntu 14.04

### ISSUE THREAD

**Issue by Pedestrian22** [chmorgan/packetnet#53]
I would like to ask you if somebody knows how to help with this problem. I cannot run my project in Ubuntu 14.04. There is missed package "**PacketDotNet**" and I need to run it in **.Net Core** project. 
Thanks for any idea and help. 

![screen1](https://user-images.githubusercontent.com/37690531/37820157-17da39fa-2e80-11e8-8407-e36a81e23a2a.png)

**Comment by chmorgan** [comment]
Hello!

Have you put a sharppcap.dll.config in place that maps wpcap to libpcap?
You'll want to do that and ensure that the libpcap name matches on that
exists on your system, sometimes its libpcap.so, othertimes libpcap.so.0.19
or whatever. I haven't found a solid way to do that across debian/ubuntu
and fedora as one has a symlink to the shorter name and the other doesn't.

**Comment by Pedestrian22** [comment]
So, after this action, should it work? I mean, is it even possible to run .Net Core with PacketDotNet/SharpPcap on Ubuntu 14.04?

**Comment by chmorgan** [comment]
I’m not sure on 14.04 but I’ve installed dotnet from Microsoft on fedora 27
and run .net core apps there.

**Comment by chmorgan** [comment]
Hi @Pedestrian22.

I've updated packetdotnet to build against .net standard 2.0. I think you'll still see an issue unless you run under mono due to the necessary library mapping. I'm looking to make it more compatible with dotnet but it would require runtime library loading and mapping and I'm not sure what the performance impact is of that approach or how much work it could be.

**Comment by nono3551** [comment]
Hi,

I am working on small packet sniffer for Linux and Windows. I didn't tested anything on Windows yet. I hope it won't be such painful for me as Linux. For Linux (Ubuntu 18.04) I made this package work in two ways:

I installed libpcap with apt-get install libpcap-dev.

1. 
I created .NET Framework 4.6.1 project. Added SharpPcap.dll.config file for mapping wpcap <= libpcap. Run MyProject.exe with mono. Everything is working.

2.
I created .NET Core 2.1 project.  Copied libpcap.so => wpcap.so. Run project with 'dotnet run' command. Everything is working.

In both approaches everything seems to be working fine but something doesn't feel right about their background. 

I new in this kind of issues. Could you please help me to chose between those two or help me find some other way to make package working on both Linux and Windows?

Thank you

**Comment by chmorgan** [comment]
Hi @nono3551. Please check out the latest sharppcap release. It has much better cross platform support that doesn't require monkeying around with libraries.

**Comment by nono3551** [comment]
Hi @chmorgan. I just checked it out and everything seems to be working fine. Thank you very much.
