### ISSUE TITLE
Suggested ReSharper fixes

### ISSUE THREAD

**Issue by Phyxion** [chmorgan/packetnet#59]
- [x] Parameter renaming, many function parameters are named with a Capital, this makes it hard to distinguish them from properties and fields.
- [x] Remove unneccessary `this`.
- [x] Replace declarations with `var` where applicable.
- [x] Use collection initializers.
- [x] Simply type names, e.g., `System.Type` can be just `Type`.
- [x] Remove redundant `else`.
- [x] Remove empty constructors
- [x] Use string interpolation instead of String.Format.

I can do this one by one, but it would require a merged PR before moving to the next point as it's too messy to put these in separate PRs all at once.

**Comment by Phyxion** [comment]
Pinging @chmorgan, if you have any feedback on this, feel free to comment here. I'll be adding suggested fixes in the first post as I find them.

**Comment by chmorgan** [comment]
Can you clarify what would change with Parameter renaming? Is it the .net recommendations of camelCase? https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-parameters

**Comment by Phyxion** [comment]
Currently a lot of parameters are named like this:
SomeMethod(Int32 **N**umber, UInt16 **A**notherName)
Which should be:
SomeMethod(Int32 **n**umber, Uint16 **a**notherName).

**Comment by chmorgan** [comment]
@Phyxion ahh ok, so good then. These all look like solid cleanup changes.

**Comment by Phyxion** [comment]
How would you receive the changes? In one go or per point? I'm not sure how well ReSharper manages with one change though as it likes to do other changes as well (along with what you changed, such as formatting changes).

**Comment by chmorgan** [comment]
If it's easy to run with all of these changes enabled and submit a PR we can look at the total number of lines changed. In one go probably makes sense as long as there are no significant functional changes. Fortunately we do have the unit tests in place and AppVeyor that helps to ensure nothing is broken.
