### ISSUE TITLE
Fancy bug.

### ISSUE THREAD

**Issue by Anandir** [chmorgan/packetnet#62]
Hi, I've found a fancy bug during some tests over a PCAP file.
During the PCAP file parsing I've got an error over this line of code:
`IPv4Packet innerIpPacket = new IPv4Packet(new PacketDotNet.Utils.ByteArraySegment(icmpPacket.PayloadData));`

I've spent a bit of time to understand why I've got this error. The only thing I've found it's a somekind of mismatch between the actual size of the IP packet and the one included within the ICMP packet (as shown in the attached image).

![screen](https://user-images.githubusercontent.com/9789409/39993581-9e6dfe42-5776-11e8-8182-8c1221c4135c.png)

I've found that PCAP on the NETRESEC page ([https://www.netresec.com/?page=PCAP4SICS](https://www.netresec.com/?page=PCAP4SICS))  and the file is the [4SICS-GeekLounge-151021.pcap](https://download.netresec.com/pcap/4sics-2015/4SICS-GeekLounge-151021.pcap) one.
The "faulty" packet is the number 499531.

I think that this kind of mismatch should be checked within the library.
The bug is present on the NuGet version and on the latest, master, version of the library.

A simple walkaround is to catch the exception, and gather all the data is possible from the original IP packet and from the ICMP packet, but everything inside the ICMP packet is "lost".

I hope that you can find a better solution for this kind of cases.

**Comment by Phyxion** [comment]
I think that packet in the pcap file is wrong, the TCP of that packet checksum is also incorrect.

**Comment by Anandir** [comment]
@Phyxion that's my suspect too, but I also think that it's something that can be addressed directly within the packet dissector inside the library.
At the end of the day Wireshark parse it without many problems.
Am I wrong?
I say so in terms of having a more resilient library. The problem can reside in the PCAP or in TCP/IP stack implementation within one of the appliance in of the test or because it's a forged packet from an "unknown player" (according to the test can be a hacker).
That's are just my two cents, simply can be a good test for the "strongness" of the library have "malformed" packets like that.

**Comment by chmorgan** [comment]
Hi @Anandir. It looks like you've identified an issue with the library. If you would be willing to submit a PR to add a test and a fix that would be great. I'm not sure any of the other developers will have a chance to fix it without your help. Closing this one out as it has been inactive for a while.
