### ISSUE TITLE
Teredo Support

### ISSUE THREAD

**Issue by patrious** [chmorgan/packetnet#65]
I am trying to parse out packets from a IPv4 UDP stream that I know in their payloads have IPv6 TCP data. They are being encapsulated using the Teredo protocol. [https://tools.ietf.org/html/rfc4380](https://tools.ietf.org/html/rfc4380)

Can packetnet be able to parse the UDP payload and notice there are embedded packets.

**Comment by chmorgan** [comment]
Hi Patrick.

It doesn’t parse these streams today but one could imagine a class that
could input udp packets that would be processed, decoded and return the
embedded packets, keeping state to handle segmentation etc.

It would be a welcome addition to the library.

Chris

**Comment by patrious** [comment]
I am not sure what you mean about keeping state and handling segmentation. Can you elaborate? I have slapped something together pretty quickly below. 

The below code can seem a little naive as we are trying to randomly parse byte[] data into packets. I can imagine we may "accidently" decode something that isn't truly a proper packet. However looking at the Teredo protocol I don't see a specific flag or magic bytes that will indicate it is a teredo protocol.

```c#
public UdpPacket(ByteArraySegment bas)
        {
            log.DebugFormat("bas {0}", bas.ToString());

            // set the header field, header field values are retrieved from this byte array
            header = new ByteArraySegment(bas);
            header.Length = UdpFields.HeaderLength;

            payloadPacketOrData = new PacketOrByteArraySegment();

            ... //Snipped

            try
            {
                // There is a protocol called Teredo that encapsulates IPv6 traffic into UDP packets.
                // We try to parse out the bytes in the payload into packets. If they contains an IPV6 packet
                // we will assign it to this current packet as a payload. https://tools.ietf.org/html/rfc4380#section-5.1.1
                var encapsulatedPacket = ParsePacket(LinkLayers.Raw, payloadPacketOrData.TheByteArraySegment.ActualBytes());
                var ipv6Tcp = encapsulatedPacket?.Extract(typeof(IPv6Packet));
                if(ipv6Tcp != null)
                    this.PayloadPacket = encapsulatedPacket;
            }
            catch (Exception)
            {
                //Try to parse the inner payload
            }
        }
```

**Comment by chmorgan** [comment]
Hi @patrious. As this hasn't been active for a while I'm closing it out. We would welcome a pull request to add this functionality but would need your help to implement it.
