### ISSUE TITLE
Can not convert a LLDP packet to bytes

### ISSUE THREAD

**Issue by UlyssesWu** [chmorgan/packetnet#8]
As description in [HERE](http://stackoverflow.com/questions/28048168/sending-an-lldp-packet-using-sharppcap-and-packet-net), when constructing a LLDP packet and getting bytes by calling `Packet.Bytes`, we will get a NullReferenceException (see the stackoverflow page for details).

And there is a workaround in that page:

```
var packet = LLDPPacket.RandomPacket();
var lldpBytes = packet.Bytes;
var lldpPacket = new LLDPPacket(new ByteArraySegment(lldpBytes));
```

After "reparsing" we can get the bytes. I think this may be a bug. [also see](https://github.com/antmicro/Packet.Net/issues/1)

**Comment by chmorgan** [comment]
Hello. If you had a .pcap file with the least number of packets required to reproduce the issue I could use that to create a unit test and fix this issue.

**Comment by UlyssesWu** [comment]
You may add a test at `LldpTest.cs` like this:

        [Test]
        public void AsPayloadTest()
        {
            PhysicalAddress NDP_MULTICAST =
           new PhysicalAddress(new byte[] { 0x01, 0x23, 0x20, 0x00, 0x00, 0x01 });
            LLDPPacket lldpPacket = new LLDPPacket();
            lldpPacket.TlvCollection.Add(new ChassisID(NDP_MULTICAST));
            lldpPacket.TlvCollection.Add(new PortID(PortSubTypes.PortComponent, BitConverter.GetBytes(6633)));
            lldpPacket.TlvCollection.Add(new TimeToLive(120));
            lldpPacket.TlvCollection.Add(new EndOfLLDPDU());
            // reparse these bytes back into a lldp packet
            //lldpPacket = new LLDPPacket(new ByteArraySegment(lldpPacket.Bytes));

            EthernetPacket ethernet = new EthernetPacket(NDP_MULTICAST, NDP_MULTICAST, EthernetPacketType.LLDP);
            ethernet.PayloadPacket = lldpPacket;
            var bytes = ethernet.Bytes;
            Assert.NotNull(bytes);
        }

It throws `NullReferenceException`. After uncomment that "reparse" line, the test would succeed. I don't know if I shouldn't call methods in that way...

**Comment by chmorgan** [comment]
Hi @UlyssesWu. I'm closing this out as it has been open for a while now but we appreciate you reporting it. We would love to have a PR to help resolve this issue and add a test for this case, we just haven't had the time to resolve it here.
