### ISSUE TITLE
attempting to set a negative length

### ISSUE THREAD

**Issue by Martin2312** [chmorgan/packetnet#87]

**Comment by Martin2312** [comment]
Hi 
I am getting an exception for some captured packets. Exception message is "attempting to set negative length of  -22". 

How is the value -22 calculated from captured packet?  Is any solution how to drop this kind of packet to avoid this exception or a solution how to handle this exception?

Thanks for any help

**Comment by chmorgan** [comment]
Hi @Martin2312. I'm closing this out as it has been open for a while. Please retest with latest version and reopen if the issue remains. We may not have the bandwidth to resolve it though and would very much welcome a pull request to correct the issue.
