### ISSUE TITLE
How can I add another protocol to Ethertype

### ISSUE THREAD

**Issue by pray4snow2** [chmorgan/packetnet#91]
Please be kind, I'm new at this....

Can anyone help me through the process of adding another Ethertype? I see that support for Profinet was added back in late 2017, but I need a very similar/related type added, Profinet MRP (PN-MRP), 0x88e3.

What I am not sure of is after I edit the appropriate file, what do I then do to get a new dll to use in my project? I am just not clear on the steps. And can I do this with VS 2015 or do I need a much newer version?

Thanks for any help.

Tom

**Comment by Phyxion** [comment]
You would need to edit the EthernetPacketType and if you want to read the Profinet packet itself you would need to add code to EthernetPacket and a class for Profinet.
At least VS 2017 is required.
