### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by nono3551** [chmorgan/packetnet#92]
Hi, I am getting error when I am trying to get Packet.TotalPacketLength in my app. Could you please look at this? Am I doing something wrong?

Packet which causes this error:

3333000000FBE88D28562B6086DD6000000004D82CFFFE80000000000000EA8D28FFFE562B60FF0200000000000000000000000000FB1100000134A858D314E914E905B04849000084000000001E0000000101320131033136380331393207696E2D61646472046172706100000C80010000007800120A50726F4E6574776F726B056C6F63616C001835302D33352D31302D37302E312050726F4E6574776F726B0C5F736C6565702D70726F7879045F756470C03B0010800100001194000100095F7365727669636573075F646E732D7364C068000C0001000011940002C05BC05B000C0001000011940002C0422D44356173456D5255574F65516F5445453843756C4B674045373766316F6C37587375384F3644755864784E6A77095F6163702D73796E63045F746370C03B0010800100001194008B2763753D34646465363562372D656539302D353535662D613561392D6632306565313465393332320D6E6D3D50726F4E6574776F726B156D61633D45383A38443A32383A35363A32423A36300F737369643D50726F4E6574776F726B2E627373696E666F3D4151494C55595949414141483649306F572B43375A48715743414141422B694E4B4676677641C07A000C0001000011940002C0D6C0D6000C0001000011940002C0A80130013601420132013601350145014601460146013801320144013801410145013001300130013001300130013001300130013001300130013001380145014603697036C020000C8001000000780002C0300A50726F4E6574776F726B085F616972706F7274C0E0001080010000119400AAA977614D413D45382D38442D32382D35362D32422D36302C72614D413D45382D38442D32382D35422D45302D42422C72614D323D45382D38442D32382D35422D45302D42432C72614E6D3D50726F4E6574776F726B2C726143683D31312C724368323D3130302C726153743D302C72614E413D302C7379466C3D3078383030432C737941503D3131372C737956733D372E362E342C737263763D37363430302E31302C626A53643D3634C07A000C0001000011940002C1F5C1F5000C0001000011940002C1EA0A50726F4E6574776F726B0C5F6465766963652D696E666FC0E000100001000011940013126D6F64656C3D416972506F7274352C313137C0420021800100000078000800000000F928C030C03000018001000000780004C0A80102C0A800218001000000780008000000001391C030C030001C8001000000780010FE80000000000000EA8D28FFFE562B60C1EA00218001000000780008000000001391C030023531033138340332353403313639C018000C8001000000780002C030C03000018001000000780004A9FEB833C07A000C000100001194000B085F616972706C6179C0E0C3A8000C000100001194000F0C4170706C6520545620283429C3A80C4170706C6520545620283429C2DB0010000100001194000C0B6D6F64656C3D4A33334150C07A000C0001000011940008055F72616F70C0E0C3FF000C000100001194001C19394332303742394239373844404170706C6520545620283429C3FFC07A000C000100001194000E0B5F746F7563682D61626C65C0E0C43B000C00010000119400131037333233423843413738383237453343C43BC07A000C000100001194000E0B5F6170706C6574762D7632C0E0255F30303030303030302D343539392D346332322D386339662D343062643964393434633565045F737562C474000C0001000011940013103733323342384341373838323745

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: startIndex
   at PacketDotNet.MiscUtil.Conversion.EndianBitConverter.CheckByteArgument(Byte[] value, Int32 startIndex, Int32 bytesRequired)
   at PacketDotNet.UdpPacket.get_DestinationPort()
   at PacketDotNet.UdpPacket.<.ctor>b__21_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at PacketDotNet.Packet.get_TotalPacketLength()
   at PacketDotNet.Packet.get_TotalPacketLength()
   at PacketDotNet.Packet.get_TotalPacketLength()
   at Shared.Core.ExtensionMethods.ConvertToStatistics(RawCapture rawCapture) in C:\Git\Katalyzer\Client\Shared\Core\ExtensionMethods.cs:line 53
   at Shared.Core.KaTaLyzerWorker.ProcessPacket(Object networkAdapter, RawCapture rawCapture) in C:\Git\Katalyzer\Client\Shared\Core\KaTaLyzerWorker.cs:line 99

**Comment by nono3551** [comment]
I was researching this problem for a while and I found that problem might be in method IPv6Packet.CalculateExtensionHeaders(). Lazy loading makes this parts hard to debug but it seems like problem is in determining IPv6ExtensionHeader.PayloadLength.

**Comment by nono3551** [comment]
Hi @chmorgan,
I don't have time for fixing this issue right now and in near future. If you want this to be fixed please assign this issue to someone else.

Thank you

**Comment by chmorgan** [comment]
Hi @nono3551. I can appreciate that. How would someone covert that packet
back into binary? If that isn’t something that can be turned into binary
can you attach a .pcap containing just that packet? Then we would be able
to attempt to reproduce the issue.

Chris

**Comment by nono3551** [comment]
This code snippet should crash application. I Also added pcap file from wireshark.

string xww ="33 33 00 00 00 FB E8 8D 28 56 2B 60 86 DD 60 00 00 00 04 D8 2C FF FE 80 00 00 00 00 00 00 EA 8D 28 FF FE 56 2B 60 FF 02 00 00 00 00 00 00 00 00 00 00 00 00 00 FB 11 00 00 01 34 A8 58 D3 14 E9 14 E9 05 B0 48 49 00 00 84 00 00 00 00 1E 00 00 00 01 01 32 01 31 03 31 36 38 03 31 39 32 07 69 6E 2D 61 64 64 72 04 61 72 70 61 00 00 0C 80 01 00 00 00 78 00 12 0A 50 72 6F 4E 65 74 77 6F 72 6B 05 6C 6F 63 61 6C 00 18 35 30 2D 33 35 2D 31 30 2D 37 30 2E 31 20 50 72 6F 4E 65 74 77 6F 72 6B 0C 5F 73 6C 65 65 70 2D 70 72 6F 78 79 04 5F 75 64 70 C0 3B 00 10 80 01 00 00 11 94 00 01 00 09 5F 73 65 72 76 69 63 65 73 07 5F 64 6E 73 2D 73 64 C0 68 00 0C 00 01 00 00 11 94 00 02 C0 5B C0 5B 00 0C 00 01 00 00 11 94 00 02 C0 42 2D 44 35 61 73 45 6D 52 55 57 4F 65 51 6F 54 45 45 38 43 75 6C 4B 67 40 45 37 37 66 31 6F 6C 37 58 73 75 38 4F 36 44 75 58 64 78 4E 6A 77 09 5F 61 63 70 2D 73 79 6E 63 04 5F 74 63 70 C0 3B 00 10 80 01 00 00 11 94 00 8B 27 63 75 3D 34 64 64 65 36 35 62 37 2D 65 65 39 30 2D 35 35 35 66 2D 61 35 61 39 2D 66 32 30 65 65 31 34 65 39 33 32 32 0D 6E 6D 3D 50 72 6F 4E 65 74 77 6F 72 6B 15 6D 61 63 3D 45 38 3A 38 44 3A 32 38 3A 35 36 3A 32 42 3A 36 30 0F 73 73 69 64 3D 50 72 6F 4E 65 74 77 6F 72 6B 2E 62 73 73 69 6E 66 6F 3D 41 51 49 4C 55 59 59 49 41 41 41 48 36 49 30 6F 57 2B 43 37 5A 48 71 57 43 41 41 41 42 2B 69 4E 4B 46 76 67 76 41 C0 7A 00 0C 00 01 00 00 11 94 00 02 C0 D6 C0 D6 00 0C 00 01 00 00 11 94 00 02 C0 A8 01 30 01 36 01 42 01 32 01 36 01 35 01 45 01 46 01 46 01 46 01 38 01 32 01 44 01 38 01 41 01 45 01 30 01 30 01 30 01 30 01 30 01 30 01 30 01 30 01 30 01 30 01 30 01 30 01 30 01 38 01 45 01 46 03 69 70 36 C0 20 00 0C 80 01 00 00 00 78 00 02 C0 30 0A 50 72 6F 4E 65 74 77 6F 72 6B 08 5F 61 69 72 70 6F 72 74 C0 E0 00 10 80 01 00 00 11 94 00 AA A9 77 61 4D 41 3D 45 38 2D 38 44 2D 32 38 2D 35 36 2D 32 42 2D 36 30 2C 72 61 4D 41 3D 45 38 2D 38 44 2D 32 38 2D 35 42 2D 45 30 2D 42 42 2C 72 61 4D 32 3D 45 38 2D 38 44 2D 32 38 2D 35 42 2D 45 30 2D 42 43 2C 72 61 4E 6D 3D 50 72 6F 4E 65 74 77 6F 72 6B 2C 72 61 43 68 3D 31 31 2C 72 43 68 32 3D 31 30 30 2C 72 61 53 74 3D 30 2C 72 61 4E 41 3D 30 2C 73 79 46 6C 3D 30 78 38 30 30 43 2C 73 79 41 50 3D 31 31 37 2C 73 79 56 73 3D 37 2E 36 2E 34 2C 73 72 63 76 3D 37 36 34 30 30 2E 31 30 2C 62 6A 53 64 3D 36 34 C0 7A 00 0C 00 01 00 00 11 94 00 02 C1 F5 C1 F5 00 0C 00 01 00 00 11 94 00 02 C1 EA 0A 50 72 6F 4E 65 74 77 6F 72 6B 0C 5F 64 65 76 69 63 65 2D 69 6E 66 6F C0 E0 00 10 00 01 00 00 11 94 00 13 12 6D 6F 64 65 6C 3D 41 69 72 50 6F 72 74 35 2C 31 31 37 C0 42 00 21 80 01 00 00 00 78 00 08 00 00 00 00 F9 28 C0 30 C0 30 00 01 80 01 00 00 00 78 00 04 C0 A8 01 02 C0 A8 00 21 80 01 00 00 00 78 00 08 00 00 00 00 13 91 C0 30 C0 30 00 1C 80 01 00 00 00 78 00 10 FE 80 00 00 00 00 00 00 EA 8D 28 FF FE 56 2B 60 C1 EA 00 21 80 01 00 00 00 78 00 08 00 00 00 00 13 91 C0 30 02 35 31 03 31 38 34 03 32 35 34 03 31 36 39 C0 18 00 0C 80 01 00 00 00 78 00 02 C0 30 C0 30 00 01 80 01 00 00 00 78 00 04 A9 FE B8 33 C0 7A 00 0C 00 01 00 00 11 94 00 0B 08 5F 61 69 72 70 6C 61 79 C0 E0 C3 A8 00 0C 00 01 00 00 11 94 00 0F 0C 41 70 70 6C 65 20 54 56 20 28 34 29 C3 A8 0C 41 70 70 6C 65 20 54 56 20 28 34 29 C2 DB 00 10 00 01 00 00 11 94 00 0C 0B 6D 6F 64 65 6C 3D 4A 33 33 41 50 C0 7A 00 0C 00 01 00 00 11 94 00 08 05 5F 72 61 6F 70 C0 E0 C3 FF 00 0C 00 01 00 00 11 94 00 1C 19 39 43 32 30 37 42 39 42 39 37 38 44 40 41 70 70 6C 65 20 54 56 20 28 34 29 C3 FF C0 7A 00 0C 00 01 00 00 11 94 00 0E 0B 5F 74 6F 75 63 68 2D 61 62 6C 65 C0 E0 C4 3B 00 0C 00 01 00 00 11 94 00 13 10 37 33 32 33 42 38 43 41 37 38 38 32 37 45 33 43 C4 3B C0 7A 00 0C 00 01 00 00 11 94 00 0E 0B 5F 61 70 70 6C 65 74 76 2D 76 32 C0 E0 25 5F 30 30 30 30 30 30 30 30 2D 34 35 39 39 2D 34 63 32 32 2D 38 63 39 66 2D 34 30 62 64 39 64 39 34 34 63 35 65 04 5F 73 75 62 C4 74 00 0C 00 01 00 00 11 94 00 13 10 37 33 32 33 42 38 43 41 37 38 38 32 37 45";

            byte[] sss = xww.Split(new[] { ' ' }).Select(y =>
            {
                return byte.Parse(Int32.Parse(y, System.Globalization.NumberStyles.HexNumber).ToString());
            }).ToArray();

            var packet = Packet.ParsePacket(LinkLayers.Ethernet, sss);

            var totalPacketLength = packet.TotalPacketLength;

[pcapExample.zip](https://github.com/chmorgan/packetnet/files/3043784/pcapExample.zip)

**Comment by chmorgan** [comment]
Great, that should help us reproduce!

**Comment by Phyxion** [comment]
This is not a valid IPv6 packet (Wireshark is also warning about it with IPv6 payload length exceeds framing length). However, the IPv6 packet extension headers implemented were't working correctly and this should be at least parsable. I'm running into this myself as well and have already addressed it (IPv6 parsing is also broken due to invalid header length). I'll commit a fix soon along with some misc.
